### ISSUE TITLE
Package does not work in Nim 2.2

### ISSUE THREAD

**Issue by xigoi** [fsh/integers#3]
The following sample code:

```nim
import pkg/integers
var n = 42'gmp
echo n
```

works fine in Nim 2.0.16. In Nim 2.2.0 and later, it produces the following error:

```
/home/adamator/.cache/nim/i_d/@mi.nim.c: In function ‘NimMainModule’:
/home/adamator/.cache/nim/i_d/@mi.nim.c:220:73: error: incompatible type for argument 1 of ‘eqdestroy___pkgZintegersZgmp_u2494’
  220 |         if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pkgZintegersZgmp_u2494(T2_); goto LA1_;}
      |                                                                         ^~~
      |                                                                         |
      |                                                                         __mpz_struct
/home/adamator/.cache/nim/i_d/@mi.nim.c:161:73: note: expected ‘__mpz_struct *’ but argument is of type ‘__mpz_struct’
  161 | static N_INLINE(void, eqdestroy___pkgZintegersZgmp_u2494)(__mpz_struct* dest_p0) {
      |                                                           ~~~~~~~~~~~~~~^~~~~~~
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3 -pthread   -I/home/adamator/.choosenim/toolchains/nim-2.2.0/lib -I/home/adamator/sandbox -o /home/adamator/.cache/nim/i_d/@mi.nim.c.o /home/adamator/.cache/nim/i_d/@mi.nim.c' failed with exit code: 1
```
